/*微猫源码 提供   QQ:2058430070   time:2018-09-16 10:08:47*/
function e(e, r, s) {
    return r in e ? Object.defineProperty(e, r, {
        value: s,
        enumerable: !0,
        configurable: !0,
        writable: !0
    }) : e[r] = s, e
}
var r, s, d = "{$_api_root}",
    a = {
        index: d + "default/index",
        default: (r = {
            indexGetPageConfig: d + "index/diy",
            BusinessPay: d + "Outprice/BusinessPay",
            orderGetPageConfig: d + "index/diy_order",
            msg_order: d + "order/msg_order",
            TuiSongList: d + "order/TuiSongList",
            HeJiangOrder: d + "order/HeJiangOrder",
            cardList: d + "Card/cardlist",
            cardmoren: d + "Card/cardmoren",
            capital: d + "User/capital",
            adimg: d + "index/adimg",
            areaLimit: d + "index/areaLimit",
            store: d + "index/store",
            stores: d + "index/stores",
            site: d + "index/site",
            getarea: d + "Address/getarea",
            user: d + "User/logins",
            insertOpenIdFormId: d + "User/insertOpenIdFormId",
            statistics: d + "User/statistics",
            userid: d + "User/getUid",
            timelist: d + "Order/Code",
            index: d + "banner/banlist",
            service: d + "index/service",
            classlist: d + "Classlist/clist",
            moneysub: d + "Takeout/BrankMoneySub",
            branklist: d + "Takeout/BrankMoneyList",
            checkcode: d + "Aliyunsms/GetSms",
            phone: d + "User/reg",
            userinfo: d + "User/userinfo",
            userinfos: d + "User/userinfos",
            uploadfile: d + "User/upload",
            attestation: d + "User/attestation",
            sellersave: d + "User/sellerSave",
            login: d + "User/userlogin",
            reset: d + "User/reset",
            getseller:d + "User/getSeller",
            addressList: d + "address/addressList",
            addslist: d + "address/addressList",
            Insprice: d + "goods/Insprice",
            distype: d + "goods/distype",
            getPhone: d + "business/getPhone",
            homeimg: d + "banner/homeimg",
            mrAddress: d + "address/mrAddress",
            classBq: d + "User/ClassBiaoQian",
            defaultsite: d + "address/defaultsite",
            siteupdate: d + "address/siteupdate",
            delAddress: d + "address/delAddress",
            addsadd: d + "address/addlist",
            times: d + "goods/times",
            time_price: d + "goods/price",
            addprice: d + "goods/addprice",
            insertorder: d + "order/insertOrder",
            insertorders: d + "order/insertOrders",
            orderpay: d + "order/orderPayParams",
            orderlist: d + "order/getOrderLists",
            orderlists: d + "order/getOrderListss",
            getOrderInfo: d + "order/getOrderInfo",
            WeightPrice: d + "goods/WeightPrice",
            ServerOrder: d + "order/ServerOrder",
            OkOrder: d + "order/OkOrder",
            OkWorth: d + "order/OkWorth",
            insertPrice: d + "order/insertPrice",
            ServerOrderInfor: d + "order/ServerOrderInfor",
            GiveOrder: d + "order/GiveOrder",
            Income: d + "order/Income",
            getLogin: d + "login/logins",
        	  sellerordersave: d + "seller/insertOrder",
            sellerindex: d + "seller/index",
            UpdateOrder: d + "seller/UpdateOrder",
            isOn : d + "seller/isOn",
            payOrder:d+"order/payOrder"
      
        }, e(r, "insertPrice", d + "order/insertPrice"), e(r, "navigation_bar_color", d + "default/navigation-bar-color"), e(r, "shop_list", d + "default/shop-list"), e(r, "navlist", d + "user/NavList"), e(r, "shop_detail", d + "default/shop-detail"), e(r, "topic_type", d + "default/topic-type"), e(r, "buy_data", d + "default/buy-data"), e(r, "goods_recommend", d + "default/goods-recommend"), e(r, "OrderUploadsImg", d + "order/OrderUploadsImg"), r),
        cart: {
            list: d + "cart/list",
            add_cart: d + "cart/add-cart",
            delete: d + "cart/delete",
            cart_edit: d + "cart/cart-edit"
        },
        card: {
            list: d + "card",
            add: d + "card/wxAdd",
            mylist: d + "card/wxlist",
            default: d + "card/defaults",
            del: d + "card/del",
            CardDefault: d + "card/CardDefault"
        },
        outprice: {
            out: d + "outprice/Send"
        },
        passport: {
            login: d + "passport/login",
            on_login: d + "passport/on-login"
        },
        order: {
            sumbit_ShenHe: d + "order/sumbit_ShenHe",
            Is_ShenHe: d + "order/Is_ShenHe",
            YesJoint: d + "order/YesJoint",
            submit_preview: d + "order/submit-preview",
            submit: d + "order/submit",
            pay_data: d + "order/pay-data",
            list: d + "order/list",
            revoke: d + "order/revoke",
            confirm: d + "order/confirm",
            count_data: d + "order/count-data",
            detail: d + "order/detail",
            refund_preview: d + "order/refund-preview",
            refund: d + "order/refund",
            refund_detail: d + "order/refund-detail",
            comment_preview: d + "order/comment-preview",
            comment: d + "order/comment",
            express_detail: d + "order/express-detail",
            clerk: d + "order/clerk",
            clerk_detail: d + "order/clerk-detail",
            get_qrcode: d + "order/get-qrcode",
            location: d + "order/location",
            out_balance: d + "order/out_balance",
            out_price: d + "order/out_price",
            balance: d + "order/balance",
            rechargePay: d + "order/rechargePay",
            pricePay: d + "order/pricePay",
            priceMsg: d + "order/priceMsg",
            orderMsg: d + "order/orderMsg",
            uploadimg: d + "order/uploadimg",
            uploadyp: d + "order/uploadyp",
            CheckOpenid: d + "order/CheckOpenid",
            confirmOrder: d + "order/confirmOrder",
            payWorth: d + "order/payWorth",
            playMsg: d + "order/playMsg",
            UpMoney: d + "Outprice/UpMoney",
            alipaySend: d + "Outprice/alipaySend",
            yezfbzj: d + "order/yezfbzj",
            commentSave: d + "order/commentSave",
            commentGet: d + "order/commentGet",
        },
        user: (s = {
            address_list: d + "user/address-list",
            mess: d + "user/mess",
            money: d + "user/money",
            enough: d + "user/enough",
            address_detail: d + "user/address-detail",
            address_save: d + "user/address-save",
            UserMember: d + "user/UserMember",
            address_set_default: d + "user/address-set-default",
            address_delete: d + "user/address-delete",
            save_form_id: d + "user/save-form-id",
            favorite_add: d + "user/favorite-add",
            favorite_remove: d + "user/favorite-remove",
            favorite_list: d + "user/favorite-list",
            index: d + "user/index",
            wechat_district: d + "user/wechat-district",
            add_wechat_address: d + "user/add-wechat-address",
            topic_favorite: d + "user/topic-favorite",
            topic_favorite_list: d + "user/topic-favorite-list",
            member: d + "user/member",
            card: d + "user/card",
            getOneFormId: d + "user/getOneFormId",
            card_qrcode: d + "user/card-qrcode",
            card_clerk: d + "user/card-clerk",
            bank: d + "user/bank",
            card_sub: d + "user/card_sub",
            
        }, e(s, "bank", d + "user/bank"), e(s, "content", d + "user/content"), e(s, "balance", d + "user/balance"), e(s, "xiaoxi", d + "user/userXuanShang"), e(s, "UserMember", d + "user/UserMember"), e(s, "usertag", d + "user/usertag"), e(s, "tagadd", d + "user/tagadd"), e(s, "tagdel", d + "user/tagdel"), e(s, "membertag", d + "user/membertag"), e(s, "qrcode", d + "user/qrcode"), e(s, "message", d + "user/message"), e(s, "rewardmoney", d + "user/rewardmoney"), e(s, "getmap", d + "user/getmap"), s),
        Coupon: {
            list: d + "coupon/couponList",
            getcoupon: d + "coupon/getcoupon",
            RedUser: d + "coupon/RedUser",
            coupon: d + "coupon/coupon",
            status: d + "coupon/status",
            actRed: d + "coupon/actRed",
            getActCoupon: d + "coupon/getActCoupon",
            getCouponList: d + "coupon/getCouponList"
        },
        message: {
            list: d + "message/listMe",
            info: d + "message/info",
            clause: d + "message/clause",
          clause: d + "message/clause",
        },
        member: {
            info: d + "member/memberinfo",
            memberinfo: d + "member/memberinfos",
            show: d + "member/show",
            sign: d + "member/sign",
            pay: d + "member/pay",
            study: d + "member/study",
            memberin: d + "member/memberin",
            viptime: d + "member/viptime",
            rebate: d + "user/get_vip"
        }
    };
module.exports = a;